# Generated by Django 5.1.1 on 2025-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('estado_Civil', models.TextField(blank=True)),
                ('edad', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('salario', models.CharField(blank=True, max_length=100)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=100)),
                ('jornada_laboral', models.CharField(blank=True, max_length=100)),
                ('arl', models.CharField(blank=True, max_length=100)),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('vacaciones', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
