# Generated by Django 5.1.1 on 2025-10-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_employee',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
