# Generated by Django 5.1.1 on 2025-04-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='cliente',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='nombre_empresa',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='telefono_contacto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
