# Generated by Django 5.1.1 on 2025-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_mantenimiento_cliente_mantenimiento_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mantenimiento', models.IntegerField()),
                ('nombre_maquina', models.CharField(max_length=200)),
                ('serial_maquina', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
