# Generated by Django 5.1.1 on 2025-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_gestion_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='nombre_maquina',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='serial_maquina',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
