# Generated by Django 5.1.1 on 2025-04-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_gestion_mantenimiento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True),
        ),
    ]
