# Generated by Django 5.1.1 on 2025-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_mantenimiento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
