# Generated by Django 5.1.1 on 2025-05-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_mantenimiento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
